name: flutter_project_pam
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  google_fonts: ^6.3.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  flutter_screenutil: ^5.9.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  http: ^1.2.2
  cupertino_icons: ^1.0.8
  uuid: ^4.5.1
  sensors_plus: ^7.0.0
  camera: ^0.11.0+2
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^6.0.0
  pdf: ^3.10.6
  printing: ^5.11.2
  share_plus: ^7.2.1
  intl: ^0.19.0
  file_picker: ^10.3.8
  fl_chart: ^1.1.1
  percent_indicator: ^4.2.5
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.4 #LOGO ATAU ICON APLIKASI
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

# IMPLEMENTASI PADA LOGO ATAU ICON 
# REFRENSI https://pub.dev/packages/flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logonotext.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/img/gambar2.png
    - assets/img/logonotext.png
    - assets/img/logoMasalah.png
    - assets/img/logoOtak.png
    - assets/img/logoMental.png
    - assets/img/ai.png
    - assets/icons/logonotext.png
    - assets/.env